### ISSUE TITLE
After help(str) example, consider adding how to exit from output.

### ISSUE THREAD

**Issue by pawlkris** [learn-co-curriculum/python-intro-to-strings#3]
It took me a bit to figure out you need to press q to escape the output... and/or ctrl+z to exit python altogether. N008$ will probably get frustrated by this. 

NOTE: Was just informed this is included in a README before the first lab, but may be good to include here, too.

**Comment by tkoar** [comment]
added a note on how to escape the terminal when your output is longer than the display.
